apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: jane
spec:
  groups:
  - system:authenticated
  usages:
  - digital signature
  - key encipherment
  - client auth
  signerName: kubernetes.io/kube-apiserver-client
  request:
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZEQ0NBVHdDQVFBd0R6RU5NQXNHQTFVRUF3d0VhbUZ1WlRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRApnZ0VQQURDQ0FRb0NnZ0VCQU9EdUpTUVA1clY2N2lNWm5VYjI3UFJuNzZHWTU0MFNhUGlrQ1BaNmJ6Y3pIUWZ2ClpuUGxBOTZPN2ZqaXROL0FhR2hUZDNtT3VjbHltbkhuSS9JUExMK1RoRVMvTXdRSnNsUERDR1hYSmpUaGxTNXUKRVk0N3o3bWxvWHJiWlk0SFdISU5TSFZQNFcxRkhKdE0xZXZNU0FSZ1hqekR1elp3VSs2VzBETHN2RlErUzNVVgora0hqd2JTd2NPRDM0OVZSR2JYYW1wVndBampDZ2JBOVJkMGMxcUhBS2E5RFFTYjlxanRRek8yV2RVSUFmN2hICjJ2MDUxMVFLRUg2Q3BHRityeW9KNlRrdE5OYld6cXl1R1AzSG1qWDVxRENiVWdNUzY2ekxkQnNiTXUra1RuQzMKRm9EVm9mSkdxYVBTVFRCd3hFb09NS0ZPcThLcXBXUklJTTJKRjdjQ0F3RUFBYUFBTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRRFlCeThqYnBGVmJsbHQ3d0hLTklUd2xNZFlEZlltU1V6am5GcjloeUttYnNvcFRsOUhsQTdhCmNuTDhhcDh2VVliekk0emNtZytUWTdzbjJXOHdkOU8waVV1Qk9sNWZWeWpxUXI3VFdtNXJsODN2YTFMSG9QZmwKZk5YeHh1TUZYSENFTHE2dnB0WkdYcG5nYmVhMVNKRkF1ZWRoMVZob05vTUVNUVluRTQ5V3VSU3EzZDFiUmM1cgpyYTRHY2ZYSkN6TDMxc25rZWduT08vNjVialpSKzMxbGh2K2VrK25LanVKeDdFNS9ESS9VVzlEU1BSUlM0SG51Ck93Q0c3b1BzcEY4RTZVZDZBQ3VVc1FNL2Izc3R5U2RvTUdSOVlTYU92bFc0cmRsV1NjZmlUc2xMcVh5aXhlYk0KZUk2cll2bGFKZ2R6YVRrSitvVjd1Z3VpVTMxNmNNT08KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
