apiVersion: v1
kind: Pod
metadata:
  name: cl-web-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.20
    command: ["sleep", "3600"]
    securityContext:
      runAsUser: 1000
      # capabilities are only supported at the container level, not the pod level
      capabilities:
        add: ["MAC_ADMIN"]
