# root@controlplane:~#  cat r.yaml 
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list","create"]

# shiftwidth=2 tabstop=2 softtabstop=-1 expandtab filetype=yaml

---
# root@controlplane:~#  cat rb.yaml 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-user-binding
roleRef:
  name: developer
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: dev-user
  kind: User
  apiGroup: rbac.authorization.k8s.io


# kubectl edit role developer -n blue
#  change to dark-blue-app
#  add list to verbs

# shiftwidth=2 tabstop=2 softtabstop=-1 expandtab filetype=yaml
