---
# ansible-playbook cluster_init.yaml -k -K
# ansible-playbook install_kubernetes_with_ansible/cluster_init.yml -e pod_network_cidr=10.244.0.0/16 -e k8s_master_ip=192.168.56.2 -l qubemaster
- hosts: masters
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: no
  connection: ssh

#  vars:
#    pod_network_manifest_file: "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
#    #pod_network_manifest_file: "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"

  vars_prompt:

  - name: "pod_network_cidr"
    prompt: "Enter the Pod Network CIDR, example: 10.244.0.0/16"
    private: no
    # https://docs.ansible.com/ansible/latest/user_guide/playbooks_prompts.html
    default: "10.244.0.0/16"

  - name: "k8s_master_ip"
    # 192.168.141.0/24 is the bridge network
    # 192.168.56.0/24 is the host-only network
    prompt: "Enter the Apiserver advertise address, example: 192.168.56.2"
    private: no
    default: "192.168.56.2"

  - name: "pod_network_manifest_file"
    prompt: "Enter the Pod network manifest file URL, Your choice could be flannel, weave or calico, etc."
    private: no

  - name: "rbac_manifest_file"
    # e.g. Calico https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml
    prompt: "Enter the RBAC manifest file URL"
    private: no

  tasks:

  - pause: seconds=5

#  - name: Resetting kubeadm
#    shell: kubeadm reset -f
#    register: output

  - name: Intializing Kubernetes Cluster
    command: kubeadm init --pod-network-cidr "{{ pod_network_cidr }}"  --apiserver-advertise-address "{{ k8s_master_ip }}" --ignore-preflight-errors=NumCPU,Mem
    run_once: true
    delegate_to: "{{ inventory_hostname }}"
    #delegate_to: "{{ k8s_master_ip }}"
    args:
      creates: /etc/kubernetes/pki/apiserver.key

  - pause: seconds=30

#  - name: Generating weave URL
#    environment:
#      KUBECONFIG: /etc/kubernetes/admin.conf
#    shell: |
#      echo "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
#    register: pod_network_manifest_file  # needs to be .stdout
#    delegate_to: "{{ inventory_hostname }}"

  - name: Create directory for kube config.
#    become_user: ansible
#    become_method: sudo
#    become: yes
    file:
      path: /home/{{ ansible_user }}/.kube
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0755

  - name: Copy /etc/kubernetes/admin.conf to user's home directory .kube/config.
#    become_user: root
#    become_method: sudo
#    become: yes
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/{{ ansible_user }}/.kube/config
      remote_src: yes
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: '0644'

  - name: Get kubeconfig file
    shell: cat /etc/kubernetes/admin.conf
    register: kubeconfig_file

  - name: Copy kubeconfig command to local file.
    # fixed by disabling ansible_become: in inventory and setting become: no in the task
    # also needs "localhost ansible_connection=local" in the inventory
    become: no
    #local_action: copy content="{{ kubeconfig_file.stdout }}" dest="kubeconfigz" mode=0600
    local_action: copy content="{{ kubeconfig_file.stdout }}" dest="/tmp/kubeconfig" mode=0600

  - pause: seconds=10

  - name: Remove the cache directory.
#    become_user: ansible
#    become_method: sudo
#    become: yes
    file:
      path: /home/{{ ansible_user }}/.kube/cache
      state: absent

  - name: Create Pod Network & RBAC.
#    become_user: ansible
#    become_method: sudo
#    become: yes
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf
    command: "{{ item }}"
#    args:
#      creates: /etc/cni/net.d/10-weave.conflist
    with_items:
      - kubectl apply -f {{ pod_network_manifest_file }}
#      - kubectl apply -f {{ rbac_manifest_file }}

  - pause: seconds=30

  - name: Get the token for joining the nodes with Kuberentes master.
    shell: kubeadm token create --print-join-command
    register: kubernetes_join_command

  - debug:
      msg: "{{ kubernetes_join_command.stdout }}"

  - name: Copy join command to local file.
    # fixed by disabling ansible_become: in inventory and setting become: no in the task
    # also needs "localhost ansible_connection=local" in the inventory
    become: no
    local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777

  - name: Configure kubectl command auto-completion.
    lineinfile:
      dest: /home/{{ ansible_user }}/.bashrc
      line: 'source <(kubectl completion bash)'
      insertafter: EOF
