---
# ansible-playbook cluster_init.yaml -k -K
# ansible-playbook install_kubernetes_with_ansible/cluster_init.yml -e pod_network_cidr=10.244.0.0/16 -e k8s_master_ip=192.168.56.2 -l qubemaster
- hosts: masters
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: no
  connection: ssh

  vars_prompt:

  - name: "pod_network_cidr"
    prompt: "Enter the Pod Network CIDR, example: 10.244.0.0/16"
    private: no
    # https://docs.ansible.com/ansible/latest/user_guide/playbooks_prompts.html
    default: "10.244.0.0/16"

  - name: "k8s_master_ip"
    # 192.168.141.0/24 is the bridge network
    # 192.168.56.0/24 is the host-only network
    prompt: "Enter the Apiserver advertise address, example: 192.168.56.2"
    private: no
    default: "192.168.56.2"

  - name: "pod_network_manifest_file"
    prompt: "Enter the Pod network manifest file URL, Your choice could be flannel, weave or calico, etc."
    private: no

  - name: "rbac_manifest_file"
    prompt: "Enter the RBAC manifest file URL"
    private: no

  tasks:

#  - name: Resetting kubeadm
#    shell: kubeadm reset -f
#    register: output

  - name: Intializing Kubernetes Cluster
    command: kubeadm init --pod-network-cidr "{{ pod_network_cidr }}"  --apiserver-advertise-address "{{ k8s_master_ip }}" --ignore-preflight-errors=NumCPU,Mem
    run_once: true
    delegate_to: "{{ inventory_hostname }}"
    #delegate_to: "{{ k8s_master_ip }}"
    args:
      creates: /etc/kubernetes/pki/apiserver.key

  - pause: seconds=30

  - name: Create directory for kube config.
#    become_user: ansible
#    become_method: sudo
#    become: yes
    file:
      path: /home/{{ ansible_user }}/.kube
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0755

  - name: Copy /etc/kubernetes/admin.conf to user's home directory .kube/config.
#    become_user: root
#    become_method: sudo
#    become: yes
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/{{ ansible_user }}/.kube/config
      remote_src: yes
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: '0644'

  - pause: seconds=10

  - name: Remove the cache directory.
#    become_user: ansible
#    become_method: sudo
#    become: yes
    file:
      path: /home/{{ ansible_user }}/.kube/cache
      state: absent

  - name: Create Pod Network & RBAC.
#    become_user: ansible
#    become_method: sudo
#    become: yes
#    environment:
#      http_proxy: wank
#      https_proxy: wank
#      no_proxy: 127.0.0.1, localhost, cloud.weave.works
#      no_proxy: 127.0.0.1, localhost
      #no_proxy: cloud.weave.works
    command: "{{ item }}"
    with_items:
       #- curl -L "{{ pod_network_manifest_file }}"
       - kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f {{ pod_network_manifest_file }}
#       - bash -c 'env;kubectl apply -f "{{ pod_network_manifest_file }}"'
#       - kubectl apply -f {{ rbac_manifest_file }}

  - name: End the play for all hosts
    meta: end_play

  - pause: seconds=30

  - name: Get the token for joining the nodes with Kuberentes master.
    shell: kubeadm token create  --print-join-command
    register: kubernetes_join_command

  - debug:
      msg: "{{ kubernetes_join_command.stdout }}"

  - name: Copy join command to local file.
    local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
